### PR TITLE
Fix regression with using closing brackets inside of class range in non-unicode mode

### LINKED ISSUE #101: Invalid error "unescaped or unmatched closing brace"
The latest Babel version (7.8.7) is using this package in the latest version (0.6.3), which now produces an error (with Babel 7.8.4 this error did not occur).

This regular expression is an absolutely valid JavaScript expression:
```
/\{([^}]+)\}/gu
```
But regjsparser throws the following error:
{code}
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: ...\src\ts\context\i18n\index.tsx: unescaped or unmatched closing brace at position 6
    \{([^}]+)\}
          ^
    at bail (...\node_modules\regjsparser\parser.js:1129:13)
    at createCharacter (...\node_modules\regjsparser\parser.js:237:11)
    at parseClassAtomNoDash (...\node_modules\regjsparser\parser.js:1105:16)
    at parseClassAtom (...\node_modules\regjsparser\parser.js:1094:16)
    at parseNonemptyClassRanges (...\node_modules\regjsparser\parser.js:1052:18)
    at parseClassRanges (...\node_modules\regjsparser\parser.js:1008:15)
    at parseCharacterClass (...\node_modules\regjsparser\parser.js:986:15)
    at parseAtom (...\node_modules\regjsparser\parser.js:649:22)
    at parseTerm (...\node_modules\regjsparser\parser.js:490:18)
    at parseAlternative (...\node_modules\regjsparser\parser.js:463:21)
    at parseDisjunction (...\node_modules\regjsparser\parser.js:443:16)
    at finishGroup (...\node_modules\regjsparser\parser.js:520:18)
    at parseGroup (...\node_modules\regjsparser\parser.js:516:14)
    at parseAtom (...\node_modules\regjsparser\parser.js:665:16)
    at parseTerm (...\node_modules\regjsparser\parser.js:490:18)
    at parseAlternative (...\node_modules\regjsparser\parser.js:463:21)
{code}

If I escape the `}`, this error does is gone:
```
/\{([^\}]+)\}/gu
```
but here, the ESLint rule "no-useless-escape", correctly complains about the useless escaping.

### PR DESCRIPTION
**Pull request by jviereck**
This is intended to fix #101, see also #100.

Note: I wrote the code to fix the bug, but I was not able to figure out what's the correct way to do here is according to the spec. If someone has a pointer to the relevant chapter in the spec, that would be great.

### CODE REVIEW

**Comment by jviereck** [comment]
?r @nicolo-ribaudo @pygy

**Comment by nicolo-ribaudo** [comment]
> Note: I wrote the code to fix the bug, but I was not able to figure out what's the correct way to do here is according to the spec. If someone has a pointer to the relevant chapter in the spec, that would be great.

I'm reading the spec, but I have never read the regexp section before :sweat_smile: 

cc @mathiasbynens Maybe you know why?

**Comment by nicolo-ribaudo** [comment]
Ok I know (for https://github.com/jviereck/regjsparser/pull/100#issuecomment-596133571).

Normally `/}/` is invalid regardless of the `u` flag, because `PatternCharacter` excludes `SyntaxCharacter` (and thus `}`).

However, we have [Annex B](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-regular-expressions-patterns). :grin:
When `u` is not present, a regex term can be an `ExtendedAtom`, which can be an `ExtendedPatternCharacter`.
`ExtendedPatternCharacter` is defined as `SourceCharacterbut not one of ^$\.*+?()[|`, so it doesn't exclude `{`.

Also, regardless of Annex B, the only characters disallowed inside a `CharacterClass` is `]` (https://www.ecma-international.org/ecma-262/10.0/index.html#prod-ClassAtomNoDash)

File: parser.js [hunk 1]
```diff
@@ -229,14 +229,14 @@
...
+    function createCharacter(matches, insideClass) {
       var _char = matches[0];
       var first = _char.charCodeAt(0);
       if (hasUnicodeFlag) {
-        if (_char === '}') {
+        if (!insideClass && _char === '}') {
           bail("unescaped or unmatched closing brace");
         }
-        if (_char === ']') {
+        if (!insideClass && _char === ']') {
```
Comment (nicolo-ribaudo) [inline parser.js]: Doesn't this change prevent this regex from throwing? `/[0-]]/u`

**Comment by jviereck** [comment]
Good catch, not sure about the example. Will check later.

File: parser.js (hunk 1 above)
Comment (jviereck) [reply parser.js]: Here is the result when running it:

```
$ regjsparser.parse('[0-]]', 'u')
Uncaught SyntaxError: unescaped or unmatched closing bracket at position 5 (parser.js:1129)
    [0-]]
         ^
    at bail (parser.js:1129)
    at createCharacter (parser.js:240)
    at parseAtom (parser.js:630)
    at parseTerm (parser.js:490)
    at parseAlternative (parser.js:463)
    at parseDisjunction (parser.js:443)
    at Object.parse (parser.js:1144)
    at <anonymous>:1:13
```

It basically parses the class range correctly `0-]` and then complains about the single `]` character.

**Comment by jviereck** [comment]
Pushed a new commit. This one parses the `ExtendedAtom` if `!hasUnicodeFlag`. Also, this allows to remove the special logic in `createCharacter`.

It should fix both #100 and #101 with a more generic implementation.

?r @nicolo-ribaudo @pygy

File: parser.js [hunk 2]
```diff
@@ -611,24 +605,36 @@
...
 
       // jviereck: allow ']', '}' here as well to be compatible with browser's
       //   implementations: ']'.match(/]/);
-      // if (res = matchReg(/^[^^$\\.*+?()[\]{}|]/)) {
-      if (res = matchReg(/^[^^$\\.*+?(){[|]/)) {
+      if (res = matchReg(/^[^^$\\.*+?()[\]{}|]/)) {
         //      PatternCharacter
         return createCharacter(res);
       }
+      else if (!hasUnicodeFlag && (res = matchReg(/^[^^$\\.*+?(){[|]/))) {
```
Comment (nicolo-ribaudo) [inline parser.js]: If we are here it means that the character isn't one of `^$\\.*+?()[\]{}|` (because of the prev `if`), and thus it should be enough to check if the character is `]` or `}`.

**Review by nicolo-ribaudo — COMMENTED** [review]
Sorry for the delay.

This commit looks good, I left a comment about a possible optimization.

File: parser.js (hunk 2 above)
Comment (jviereck) [reply parser.js]: Good point. I was thinking about it initially but then thought the readability of having the full string might be better. Given your comment I just pushed an optimized version as `res = matchReg(/^(?:]|})/))`.
