### PR TITLE
fix: do not create back reference inside ch class

### LINKED ISSUE #114: Decimal escape in capture group is incorrectly parsed as a reference
[AST Explorer](https://astexplorer.net/#/gist/645058e4e806ab9ef8a3ff507e9591f3/77a927eb6ab05edfd794e5f5565012a500d49ed1).

Currently,

```
/([\1])/
```

is parsed as

```json
{
  "type": "group",
  "behavior": "normal",
  "body": [
    {
      "type": "characterClass",
      "body": [
        {
          "type": "reference",
          "matchIndex": 1,
          "range": [
            2,
            4
          ],
          "raw": "\\1"
        }
      ],
      "negative": false,
      "range": [
        1,
        5
      ],
      "raw": "[\\1]"
    }
  ],
  "range": [
    0,
    6
  ],
  "raw": "([\\1])"
}
```

where `\1` should have been parsed as a value.

### PR DESCRIPTION
**Pull request by JLHwung**
Fixes #114.

Per spec, the `CharacterRanges` does not cover `AtomEscape`, so `\NonZeroDecimalDigit` must be parsed as an value.

When Unicode mode is on, the only valid decimal escape is `\0`.

### CODE REVIEW

File: parser.js [hunk 1]
```diff
@@ -841,16 +841,26 @@
...
 
-      var res, match;
+      var res, match, from = pos;
+
+      if (hasUnicodeFlag) {
+        if (res = matchReg(/^\d/)) {
+          if (res[0] !== "0" || (res = matchReg(/^\d/)) ) {
+            bail("Invalid decimal escape in unicode mode", null, from, pos);
+          }
+          return createEscaped('null', 0x0000, '0', 1);
```
Comment (tjenkinson) [inline parser.js:855]: Is `\000` also allowed in Unicode mode?

looks like it is treated as null further down

Comment (JLHwung) [reply parser.js:855]: I don't think it is allowed. Both Gecko and JSC throw on `/\000/u`.

**Comment by jviereck** [comment]
Thanks for providing the fix. This looks good!
